apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: "{{ .Values.name }}"

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  serviceName: "{{ .Values.name }}"
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/mysql_password_secret.yaml") . | sha256sum }}
      labels:
        app: "{{ .Values.name }}"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: "{{ .Values.name }}"
        image: {{ .Values.statefulset.image }}:{{ .Values.statefulset.tag }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/minesql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.name }}"
                key: MYSQL_ROOT_PASSWORD
        {{- if .Values.statefulset.resources }}
        resources:
          {{- if .Values.statefulset.resources.requests }}
          requests:
            memory: {{ .Values.statefulset.resources.requests.memory | default "50Mi" | quote }}
            cpu: {{ .Values.statefulset.resources.requests.cpu | default "10m" | quote }}
          {{- else}}
          requests:
            memory: "50Mi"
            cpu: "10m"
          {{- end}}
          {{- if .Values.statefulset.resources.limits }}
          limits:
            memory: {{ .Values.statefulset.resources.limits.memory | default "1024Mi" | quote }}
            cpu: {{ .Values.statefulset.resources.limits.cpu | default "1" | quote }}
          {{- else}}  
          limits:
            memory: "1024Mi"
            cpu: "1"
          {{- end }}
        {{- else }}
        resources:
          requests:
            memory: "60Mi"
            cpu: "12m"
          limits:
            memory: "1030Mi"
            cpu: "1"
        {{- end}} 
  volumeClaimTemplates:
  - metadata:
      name: mysql-store
    spec:
      accessModes: 
        - ReadWriteOnce
      storageClassName: "manual"
      resources:
        requests:
          storage: 5Gi
