apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Values.name }}-client"
spec:
  containers:
  - name: "{{ .Values.name }}"
    image: alpine
    command: ['sh','-c', "sleep 1800m"]
    imagePullPolicy: IfNotPresent
